// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, unnecessary_const
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
 // ignore: unused_import
 import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyBvfl870NdvML314PADCkVS8KCnL7_lO18',
    appId: '1:661372071003:web:a3221d9dfa71ccc3e7a37e',
    messagingSenderId: '661372071003',
    projectId: 'chatappflutter-96fbc',
    authDomain: 'chatappflutter-96fbc.firebaseapp.com',
    storageBucket: 'chatappflutter-96fbc.appspot.com',
    measurementId: 'G-SX1VDCEKZ7',
  );

  static const FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBYfRNeBuxWg3SdPmZz_nsuIVL7HopzikE',
    appId: '1:661372071003:android:f1fbab5c434d1eefe7a37e',
    messagingSenderId: '661372071003',
    projectId: 'chatappflutter-96fbc',
    storageBucket: 'chatappflutter-96fbc.appspot.com',
  );

  static const FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyCAQjld_QdCGWpMbuTuV1bO6aBLpzukN2A',
    appId: '1:661372071003:ios:a38b3fcc471877c1e7a37e',
    messagingSenderId: '661372071003',
    projectId: 'chatappflutter-96fbc',
    storageBucket: 'chatappflutter-96fbc.appspot.com',
    iosClientId: '661372071003-d6cvmqb1ut44pgvsrqn8jtgn58392kmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
